# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleMapsEx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleMapsEx
pod 'GoogleMaps'
pod 'GooglePlacePicker'
pod 'GooglePlaces'
pod 'Alamofire', '~> 4.7'
pod 'SwiftyJSON', '~> 4.0'
pod 'SQLite.swift', '~> 0.12.0'

end
